### ISSUE TITLE
Database primary keys

### ISSUE THREAD

**Issue by luisfernrg** [mattheath/kala#3]
I'm looking for an alternative to incremental keys in MySQL I wondering if this would be a good option?

**Comment by mattheath** [comment]
This will give you unique IDs which are roughly ordered (k-sorted) by time, so its definitely one option, but it depends on your requirements!

As an example, auto-incrementing IDs in mysql are sequential numbers based on the time they were created, and preserve this absolute ordering. Whereas IDs generated across multiple Kala workers will be guaranteed to be unique, but may be incorrectly ordered within a period up to the total clock skew of your systems. The advantage is that they are still sortable, and ID generation can proceed without coordination with a central system, which is useful in a distributed system.

We use Kala at @monzo to generate unique IDs (primary keys in cassandra) for almost all objects in our systems, however to make them more human readable (shorter) we encode the resulting numeric IDs using [base62](https://github.com/mattheath/base62). We also zero-pad these to ensure they are still lexically sortable as the length of the ID increases. This gives us something like:

`340282366920938463463374607431768211455 ` => `00007n42DGM5Tflk9n8mt7Fhc7`

Hope that helps! 😃

**Comment by luisfernrg** [comment]
@mattheath thank you exactly what I needed, great explanation as well I very much appreciate it!
